version: '3.8'

services:
  history-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=chat_history
      - KAFKA_SERVERS=kafka:29092
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

networks:
  default:
    external:
      name: genie-chat-service_default